- hosts: all
  become: yes
  vars_files:
    - ansible-vars.yaml
  roles:
    - common

- hosts: quobyte_servers
  become: yes
  vars_files:
    - ansible-vars.yaml
  roles:
    - common-quobyte-server

- hosts: quobyte_servers[0]
  become: yes
  vars_files:
    - ansible-vars.yaml
  roles:
    - quobyte-bootstrap

- hosts: quobyte_servers[1:2]
  vars_files:
    - ansible-vars.yaml
  become: yes
  roles:
    - quobyte-registry

- hosts: quobyte_servers
  become: yes
  vars_files:
    - ansible-vars.yaml
  roles:
    - quobyte-server

- hosts: quobyte_clients
  vars_files:
    - ansible-vars.yaml
  become: yes
  roles:
    - quobyte-client

- hosts: quobyte_servers[0]
  tasks:
    - name: Waiting for 60 seconds to ensure all devices are detected
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost

    - name: Format all devices
      ansible.builtin.shell: |
         for dev in $(qmgmt -o csv device list-unformatted | awk -F',' 'NR > 1 && $3 ~ /\/dev\/sdc$/ {print $1}'); do qmgmt device make $dev M; done
         for dev in $(qmgmt -o csv device list-unformatted | awk -F',' 'NR > 1 && $3 ~ /\/dev\/(sdb|sdd|sde|sdf)$/ {print $1}'); do qmgmt device make $dev D; done
         for dev in $(qmgmt -o csv device list-unformatted | awk -F',' 'NR > 1 && $3 ~ /\/dev\/nvme0/ {print $1}'); do qmgmt device make --tags scratch-device $dev M; done
         for dev in $(qmgmt -o csv device list-unformatted | awk -F',' 'NR > 1 && $3 ~ /\/dev\/nvme[1-9]/ {print $1}'); do qmgmt device make --tags scratch-device $dev D; done

    - name: Display Quobyte Access Info
      debug:
        msg:
          - "-----------------------------------------------------------------------------------------"
          - "🚀 QUOBYTE INSTALLATION COMPLETE!"
          - "   Please log into the Quobyte webconsole for the next steps: "
          - "   http://{{ hostvars[groups['quobyte_servers'][0]]['ansible_host'] }}:8080"
          - "   Please use the credentials configured in your terraform.tfvars"
          - "-----------------------------------------------------------------------------------------"
